sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
branches:
  only:
    - master
before_install:
  - npm i -g npm@^2.0.0
script:
  - npm run build
after_success:
  - npm publish
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
